kind: Secret
apiVersion: v1
metadata:
  name: connection-secret
data:
  connection-string: UjAxOTVGRVBBNUNFWEpRU1RSNERNWTFHNzBNQVVGSkU=
---
# webpage deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  labels:
    app: webpage
spec:
  replicas: 1 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: connection-secret    
      containers:
      - name: webpage #1st container
        image: jhohandx/static-page:5daacf49569aaf0a9a7a067f82af87a08786feb462204ed914d98cd2c7e4329c
        ports:
        - containerPort: 8084 #Exposes the port 8084 of the container
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
        env:
        - name: PORT
          value: "8084"
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: connection-secret
              key: connection-string          
---
kind: Service
apiVersion: v1
metadata:
  name: webpage-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: webpage
  ports:

  - name: webpage-tcp-port
    protocol: TCP
    port: 8084
    targetPort: 8084


# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: webpage
# subsets:
#   - addresses:
#       - ip: 10.43.86.10
#     ports:
#       - port: 9376
