# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - vsts/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: cat /etc/*release
  displayName: 'Run a one-line script'

- script: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    pip install awscli
  displayName: 'Run a multi-line script'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'sc-test'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      aws sts get-caller-identity
      aws sts assume-role --role-arn arn:aws:iam::772967566311:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_5e46d932740a76d9 --role-session-name vsts
      aws sts assume-role --role-arn arn:aws:iam::772967566311:role/lambda-role --role-session-name vsts

- task: SSH@0
  inputs:
    sshEndpoint: 'sc-ssh'
    runOptions: 'commands'
    commands: 'kubectl get po -owide'
    readyTimeout: '20000'
