# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'workflows/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run o
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64;sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          minikube start;
          kubectl get po -A;
          pwd;
          ls -ll;
          sudo apt-get update -y;
          sudo apt-get install -y net-tools;
          kubectl apply -f https://k8s.io/examples/service/load-balancer-example.yaml;
          kubectl expose deployment hello-world --type=LoadBalancer --name=my-service;
          sleep 3m;
          kubectl get services my-service;
          kubectl describe services my-service;
          kubectl get all
          kubectl get pods -o wide
          sleep 3m
          ifconfig
