name: kubernetes webpage

on: [push]
jobs:

  buildimages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -   name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker build csharp
      run: |
        git clone https://github.com/jhohandx/gitActions.git;pwd
        #shm_id=$(sha256sum  /home/runner/work/gitActions/gitActions/vsts/webpage/Dockerfile
        ls /home/runner/work/gitActions/gitActions/vsts/webpage/
        echo ${{ github.event.pull_request.head.sha }}
        docker build /home/runner/work/gitActions/gitActions/vsts/webpage/ -t jhohandx/static-page:${{ github.event.pull_request.head.sha }}
    - name: docker push
      run: |
        docker push jhohandx/static-page:${{ github.event.pull_request.head.sha }}
          
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build_webpage_image
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: shm_id=$(sha256sum  /home/ec2-user/bancolombia/lab/webpage/Dockerfile | awk '{print $1}');docker build --tag jhohandx/static-page:$shm_id /home/ec2-user/bancolombia/lab/webpage;sudo docker push jhohandx/static-page:$shm_id
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
      env:
        CI: true
  
  deploy:
    name: deploy_webpage_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get svc;git clone https://github.com/jhohandx/gitActions.git /github/workspace/gitActions;kubectl apply -f /github/workspace/gitActions/vsts/webpage/webpage.yml;pwd

