name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        shm_id=$(sha256sum  Dockerfile | awk '{print $1}')  

    # Runs docker build
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$shm_id

