name: kubernetes webpage

on: [push]
jobs:
#  pre-build:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: clone repository
#         run: git clone https://github.com/jhohandx/gitActions.git 

#       # Runs a set of commands using the runners shell
#       - name: build image
#         run: |
#           echo docker build test;ls gitActions;pwd
#           shm_id=$(sha256sum  /home/runner/work/gitActions/gitActions/vsts/webpage/Dockerfile | awk '{print $1}')
#           echo $shm_id
#           #docker build --tag jhohandx/static-page:$shm_id /home/runner/work/gitActions/gitActions/gitActions/vsts/webpage
#           #sudo docker push jhohandx/static-page:$shm_id
          
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build_webpage_image
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: shm_id=$(sha256sum  /home/ec2-user/bancolombia/lab/webpage/Dockerfile | awk '{print $1}');docker build --tag jhohandx/static-page:$shm_id /home/ec2-user/bancolombia/lab/webpage;sudo docker push jhohandx/static-page:$shm_id
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
      env:
        CI: true
  
  deploy:
    name: deploy_webpage_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get svc;git clone https://github.com/jhohandx/gitActions.git /github/workspace/gitActions;kubectl apply -f /github/workspace/gitActions/vsts/webpage/webpage.yml;pwd

