name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: commands to ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: kubectl apply -f /home/ec2-user/bancolombia/lab/webpage/webpage.yml
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
      env:
        CI: true      
