name: kubernetes webpage

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build_webpage_image
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: shm_id=$(sha256sum  /home/ec2-user/bancolombia/lab/webpage/Dockerfile | awk '{print $1}');docker build --tag jhohandx/static-page:$shm_id /home/ec2-user/bancolombia/lab/webpage;sudo docker push jhohandx/static-page:$shm_id
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
      env:
        CI: true
  
  deploy:
    name: deploy_webpage_service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get svc;git clone https://github.com/jhohandx/gitActions.git /github/workspace/gitActions;kubectl apply -f /github/workspace/gitActions/vsts/webpage/webpage.yml;pwd
#     - name: verify deployment
#       uses: steebchen/kubectl@master
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         KUBECTL_VERSION: "1.15"
#       with:
#         args: '"rollout status deployment/my-app"'
