name: kubernetes-jhohandx/static-page
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pipeline.yml
      - vsts/webpage/**

jobs:
  ssh-commands:
#     runs-on: ubuntu-latest
#     steps:
#     - name: build_webpage_image
#       uses: garygrossgarten/github-action-ssh@release
#       with:
#         command: sudo yum update;sudo yum -y install git;curl -sfL https://get.k3s.io | sh -;sudo chmod 777  /etc/rancher/k3s/k3s.yaml;sudo yum update -y;sudo amazon-linux-extras install docker;sudo yum -y install docker;sudo service docker start;sudo usermod -a -G docker ec2-user
#         host: ${{ secrets.REMOTE_HOST }}
#         username: ${{ secrets.REMOTE_USER }}
#         privateKey: ${{ secrets.SERVER_SSH_KEY }}
#       env:
#         CI: true
        
    - name: baseline
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo yum update;sudo yum -y install git;curl -sfL https://get.k3s.io | sh -;sudo chmod 777  /etc/rancher/k3s/k3s.yaml;sudo yum update -y;sudo amazon-linux-extras install docker;sudo yum -y install docker;sudo service docker start;sudo usermod -a -G docker ec2-user
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}     
      
  make-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -   name: login-dockerHub #login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     

    - name: build-image # build image
      run: |
        git clone https://github.com/jhohandx/gitActions.git;pwd
        ls /home/runner/work/gitActions/gitActions/vsts/webpage/
        echo ${{ github.sha }}
        docker build /home/runner/work/gitActions/gitActions/vsts/webpage/ -t jhohandx/static-page:${{ github.sha }}
        export imageid=${{ github.sha }}
    - name: push-image-to-dockerHub
      run: |
        docker push jhohandx/static-page:${{ github.sha }}          
  
  deploy-kubernets:
    name: deploy-image-to-kubernetes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: update-static-page
      uses: steebchen/kubectl@master 
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get svc;sudo git clone https://github.com/jhohandx/gitActions.git /github/workspace/gitActions;kubectl apply -f /github/workspace/gitActions/vsts/webpage/webpage.yml;kubectl set image deployment/webpage-deployment webpage=jhohandx/static-page:${{ github.sha }}


        
