name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: commands to ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: git clone https://github.com/jhohandx/gitActions.git /home/ec2-user/bancolombia/gitActions;kubectl apply -f /home/ec2-user/bancolombia/gitActions/vsts/webpage/webpage.yml;pwd
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
      env:
        CI: true      

  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get svc;git clone https://github.com/jhohandx/gitActions.git /github/workspace/gitActions;kubectl apply -f /github/workspace/gitActions/vsts/webpage/webpage.yml;pwd
#     - name: verify deployment
#       uses: steebchen/kubectl@master
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         KUBECTL_VERSION: "1.15"
#       with:
#         args: '"rollout status deployment/my-app"'
